version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql-database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
